### ISSUE TITLE
How to calculate TTC and PET

### ISSUE THREAD

**Issue by ghost** [FinestStone/AV-Interactions-City-Traffic#1]
Hello!

Thanks for sharing the code!

I am just wondering how you calculated the TTC and PET based on the trajectory data? More precisely, how did you determine if a pair of vehicles are conflicted?

Thanks.

**Comment by FinestStone** [comment]
Hi,

TTC and PET are calculated using timeToCollision and computePET implemented in the python package [Traffic Intelligence](https://bitbucket.org/Nicolas/trafficintelligence/src/master/). All safety indicators were computed using the script [safety-analysis.py](http://132.207.98.161:3000/file/61248f2cd459/scripts/safety-analysis.py) from the same python package.

More details can be found in our article : É. Beauchamp, N. Saunier and M.-S. Cloutier. Study of Automated Shuttle Interactions in City Traffic Using Surrogate Measures ofSafety. In Transportation Research Board Annual Meeting, 2021

Hope this helps,

Étienne

**Comment by ghost** [comment]
I entered the command in the website (hg clone http://132.207.98.161:3000/ <destination directory>) to the terminal. But an error occurred: 

abort: HTTP Error 404: Not Found

Could you please help me figure it out?

Thanks.

**Comment by FinestStone** [comment]
Hi,

Unfortunately, I do not take part in the development of this package. It might be deprecated. You can try addressing your issues directly to the concerned contributors.

Regards,

Étienne

**Comment by nsaunier** [comment]
The server for the Traffic Intelligence mercurial repository was down. It's back up.
